
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzceiyfimcamoywujsid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y2VpeWZpbWNhbW95d3Vqc2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDc1MDcsImV4cCI6MjA2MzQyMzUwN30.Iva7roo_p8PJF2p3a33mX-aKIVFXoD2wC8AET76HIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true
  }
});

// Helper function to track product clicks
export const trackProductClick = async (productId: string, source: string = 'unknown') => {
  try {
    const { error } = await supabase
      .from('product_clicks')
      .insert({
        product_id: productId,
        referrer: document.referrer || null,
        user_agent: navigator.userAgent || null,
        source: source // Track the source of the click
      });
      
    if (error) {
      console.error('Error tracking product click:', error);
    }
  } catch (err) {
    console.error('Failed to track product click:', err);
  }
};

// Helper function to track promotion area clicks
export const trackPromotionClick = async (productId: string, promotionArea: string, blogId?: string) => {
  try {
    // Use any type to bypass TypeScript check until the types are regenerated
    const { error } = await (supabase as any)
      .from('promotion_clicks')
      .insert({
        product_id: productId,
        promotion_area: promotionArea,
        blog_id: blogId || null,
        referrer: document.referrer || null,
        user_agent: navigator.userAgent || null
      });
      
    if (error) {
      console.error('Error tracking promotion click:', error);
    }
  } catch (err) {
    console.error('Failed to track promotion click:', err);
  }
};

// Helper function to track blog post views
export const trackBlogView = async (blogId: string, source: string = 'unknown') => {
  try {
    const { error } = await (supabase as any)
      .from('blog_views')
      .insert({
        blog_post_id: blogId,
        referrer: document.referrer || null,
        user_agent: navigator.userAgent || null,
        source: source
      });
      
    if (error) {
      console.error('Error tracking blog view:', error);
    }
  } catch (err) {
    console.error('Failed to track blog view:', err);
  }
};

