// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzceiyfimcamoywujsid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6Y2VpeWZpbWNhbW95d3Vqc2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDc1MDcsImV4cCI6MjA2MzQyMzUwN30.Iva7roo_p8PJF2p3a33mX-aKIVFXoD2wC8AET76HIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);